# Generated by Django 3.1.2 on 2021-01-19 12:51

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisements',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisement', verbose_name='Image')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link')),
                ('m_img', models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Mobile Banner')),
            ],
        ),
        migrations.CreateModel(
            name='announce',
            fields=[
                ('an_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Announcements')),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='banner',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Banner')),
            ],
        ),
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('discuss_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='content', verbose_name='Image')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='Likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Event', verbose_name='Event Photo')),
                ('event_slug', models.CharField(max_length=255)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 18, 21, 32, 935626))),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gallery Title')),
                ('desc', models.TextField()),
                ('event_for', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.event')),
            ],
        ),
        migrations.CreateModel(
            name='performer',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Emp Code')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Message')),
                ('date_published', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 18, 21, 32, 935626))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='EMP Code')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='Profile', verbose_name='Profile Photo')),
                ('dob', models.CharField(blank=True, max_length=50, null=True, verbose_name='D.O.B')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('web_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Address')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('hire_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hire Date')),
                ('about', models.TextField(blank=True, max_length=100, null=True, verbose_name='About')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('zone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone')),
                ('aniversary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aniversary')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('reporting_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reporting To')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='Cover')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discussion')),
                ('userlikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='galleryPhoto',
            fields=[
                ('gp_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Gallery', verbose_name='Gallery Photo')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gallery')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Performer Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Performer')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('perform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.performer')),
            ],
        ),
    ]
