# Generated by Django 3.1.2 on 2020-11-12 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201111_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='m_img',
            field=models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Mobile Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 10, 14, 975923)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 10, 14, 960410)),
        ),
    ]
