# Generated by Django 3.1.2 on 2020-11-12 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201112_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='m_img',
        ),
        migrations.AddField(
            model_name='advertisements',
            name='m_img',
            field=models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Mobile Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 11, 45, 873234)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 18, 11, 45, 872237)),
        ),
    ]
