# Generated by Django 3.1.2 on 2020-11-19 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201113_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 56, 58, 885311)),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='Gallery', verbose_name='Gallery Photo'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 10, 56, 58, 885311)),
        ),
    ]
