# Generated by Django 3.1.2 on 2021-02-03 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210201_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 12, 32, 58, 781635)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 12, 32, 58, 781635)),
        ),
    ]
