# Generated by Django 3.1.2 on 2020-11-19 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201119_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='profile_photo',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 12, 53, 6, 182628)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 12, 53, 6, 182628)),
        ),
    ]
