# Generated by Django 3.1.2 on 2020-11-26 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201119_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 32, 8, 403624)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 26, 16, 32, 8, 403624)),
        ),
        migrations.DeleteModel(
            name='userPhoto',
        ),
    ]
