# Generated by Django 3.1.2 on 2020-11-30 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201130_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphoto',
            name='id',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 24, 24, 870727)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 14, 24, 24, 870727)),
        ),
    ]
