# Generated by Django 3.1.2 on 2020-11-30 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201130_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 15, 29, 30, 278644)),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 15, 29, 30, 272103)),
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
